version: "3.9"
services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    ports:
    - 4444:4444  
  tensorflow:
    build: 
        context: .
        dockerfile: Dockerfile.cpu
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ".:/app"
      - "./notebooks:/tf/notebooks"
